### ISSUE TITLE
"too many redirects" error from sample search

### ISSUE THREAD

**Issue by bbuzzell** [birkin/easyaccess_project#36]
The first book example on testing page (https://library.brown.edu/easyaccess/find/) returns error: "The library.brown.edu page isn’t working
library.brown.edu redirected you too many times.
ERR_TOO_MANY_REDIRECTS".
https://library.brown.edu/easyaccess/borrow/login/?sid%3DFirstSearch%3AWorldCat%26genre%3Dbook%26isbn%3D9780439339117%26title%3DZen%2Bshorts%26date%3D2005%26aulast%3DMuth%26aufirst%3DJon%26auinitm%3DJ%26id%3Ddoi%3A%26pid%3D53084041%26url_ver%3DZ39.88-2004%26rfr_id%3Dinfo%3Asid/firstsearch.oclc.org%3AWorldCat%26rft_val_fmt%3Dinfo%3Aofi/fmt%3Akev%3Amtx%3Abook%26rft.genre%3Dbook%26rfe_dat%3D%253Caccessionnumber%253E53084041%253C/accessionnumber%253E%26rft_id%3Dinfo%3Aoclcnum/53084041%26rft_id%3Durn%3AISBN%3A9780439339117%26rft.aulast%3DMuth%26rft.aufirst%3DJon%26rft.auinitm%3DJ%26rft.btitle%3DZen%2Bshorts%26rft.date%3D2005%26rft.isbn%3D9780439339117%26rft.place%3DNew%2BYork%26rft.pub%3DScholastic%2BPress%26rft.edition%3D1st%2Bed. - Bonnie 3/29/16

**Comment by bbuzzell** [comment]
Same problem on second book example also when choosing "request via easy borrow"- here's the landing page: https://library.brown.edu/easyaccess/borrow/availability/?sid=FirstSearch%3AWorldCat&genre=book&title=Zen&date=1978&aulast=Yoshioka&aufirst=T%C5%8Dichi&id=doi%3A&pid=6104671%3Cfssessid%3E0%3C%2Ffssessid%3E%3Cedition%3E1st+ed.%3C%2Fedition%3E&url_ver=Z39.88-2004&rfr_id=info%3Asid%2Ffirstsearch.oclc.org%3AWorldCat&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&rft.genre=book&req_dat=%3Csessionid%3E0%3C%2Fsessionid%3E&rfe_dat=%3Caccessionnumber%3E6104671%3C%2Faccessionnumber%3E&rft_id=info%3Aoclcnum%2F6104671&rft.aulast=Yoshioka&rft.aufirst=T%C5%8Dichi&rft.btitle=Zen&rft.date=1978&rft.place=Osaka++Japan&rft.pub=Hoikusha&rft.edition=1st+ed.&rft.genre=book -

**Comment by birkin** [comment]
I and B.B. unable to duplicate. Marking this as closed but will reopen if problem recurs.
